[project]
name = "electoralyze"
description = "Add a short description here"
authors = [{name = "Andre Medina", email = "AndreMedina@hotmail.com.au"}]
readme="README.md"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["electoralyze"]

[tool.hatch.build.targets.wheel.sources]
"electoralyze" = "electoralyze"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = "../.."

[tool.hatch.metadata]
allow-direct-references = true

[project.entry-points.pytest11]
region_fixture = "electoralyze.common.testing.region_fixture"
census_fixture = "electoralyze.common.testing.census_fixture"
election_fixture = "electoralyze.common.testing.election_fixture"
