[project]
channels = ["conda-forge"]
platforms = ["linux-64"]
name = "vision"

[environments]
ui = { features = ["ui"], solve-group = "default"}
dev = { features = ["dev","ui"], solve-group = "default"}
default = { features = ["dev", "ui"], solve-group = "default"}

[pypi-dependencies]
electoralyze = { path = "packages/electoralyze", editable = true }

[feature.ui.pypi-dependencies]
ui = { path = "packages/ui", editable = true }

[tasks]
tests = "pytest -v packages/electoralyze/tests"

[feature.dev.tasks]
test_all = "pytest -v packages"

[feature.ui.dependencies]
dash = ">=2.18.1,<3"

[dependencies]
rich = ">=13.9.3,<14"
pytest = "*"
pre-commit = ">=4.0.1,<5"
ipykernel = ">=6.29.5,<7"
