name: Integration Tests
on:
  pull_request:
    branches:
      - '**'

jobs:
  integration_tests:
    name: pixi run integration
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # FIXME: Setup git LFS #10
      # - name: Pixi Setup
      #   uses: prefix-dev/setup-pixi@v0.8.1
      #   with:
      #     pixi-version: v0.33.0
      #     cache: true
      #
      # - name: Check Pixi installed
      #   run: |
      #     pixi --version
      #     which pixi
      #     pixi run which python
      #
      # - name: Run integration test with Pixi
      #   run: |
      #     pixi run integration
