name: Unit Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  unit_tests:
    name: pixi run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pixi Setup
        uses: prefix-dev/setup-pixi@v0.8.4
        with:
          pixi-version: v0.33.0
          cache: true

      - name: Check Pixi installed
        run: |
          pixi --version
          which pixi
          pixi run which python

      - name: Run tests with Pixi
        run: |
          pixi run tests
