name: Validate Branch

on:
  push:
    branches:
      - '**'

jobs:
  validate-branch-name:
    name: branch name
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false
